<?php

namespace ContainerW6OHX34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NTkc4CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n_tkc4C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n_tkc4C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'command' => ['privates', '.errored..service_locator.n_tkc4C.App\\Entity\\Command', NULL, 'Cannot autowire service ".service_locator.n_tkc4C": it references class "App\\Entity\\Command" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'command' => 'App\\Entity\\Command',
            'entityManager' => '?',
        ]);
    }
}
