<?php

namespace ContainerW6OHX34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.n_tkc4C.App\Entity\Command' shared service.
     *
     * @return \App\Entity\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.n_tkc4C": it references class "App\\Entity\\Command" but no such service exists.');
    }
}
