<?php

namespace ContainerR2TbmsD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TlXIq3_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tlXIq3.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tlXIq3.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CartController::add' => ['privates', '.service_locator.5OibA2.', 'get_ServiceLocator_5OibA2_Service', true],
            'App\\Controller\\CartController::delete' => ['privates', '.service_locator.5OibA2.', 'get_ServiceLocator_5OibA2_Service', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\CartController::remove' => ['privates', '.service_locator.5OibA2.', 'get_ServiceLocator_5OibA2_Service', true],
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.4Uu00Y_', 'get_ServiceLocator_4Uu00YService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.4Uu00Y_', 'get_ServiceLocator_4Uu00YService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.7P87fGM', 'get_ServiceLocator_7P87fGMService', true],
            'App\\Controller\\CommandController::add' => ['privates', '.service_locator.aVHk8q.', 'get_ServiceLocator_AVHk8q_Service', true],
            'App\\Controller\\CommandController::index' => ['privates', '.service_locator.x0TjW_X', 'get_ServiceLocator_X0TjWXService', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.1QZmUjg', 'get_ServiceLocator_1QZmUjgService', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.A3CoJWz', 'get_ServiceLocator_A3CoJWzService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\ProductController::new' => ['privates', '.service_locator.Hjz3HR0', 'get_ServiceLocator_Hjz3HR0Service', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.5OibA2.', 'get_ServiceLocator_5OibA2_Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.lwhU4dN', 'get_ServiceLocator_LwhU4dNService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\CartController:add' => ['privates', '.service_locator.5OibA2.', 'get_ServiceLocator_5OibA2_Service', true],
            'App\\Controller\\CartController:delete' => ['privates', '.service_locator.5OibA2.', 'get_ServiceLocator_5OibA2_Service', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\CartController:remove' => ['privates', '.service_locator.5OibA2.', 'get_ServiceLocator_5OibA2_Service', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.4Uu00Y_', 'get_ServiceLocator_4Uu00YService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.4Uu00Y_', 'get_ServiceLocator_4Uu00YService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.7P87fGM', 'get_ServiceLocator_7P87fGMService', true],
            'App\\Controller\\CommandController:add' => ['privates', '.service_locator.aVHk8q.', 'get_ServiceLocator_AVHk8q_Service', true],
            'App\\Controller\\CommandController:index' => ['privates', '.service_locator.x0TjW_X', 'get_ServiceLocator_X0TjWXService', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.1QZmUjg', 'get_ServiceLocator_1QZmUjgService', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.A3CoJWz', 'get_ServiceLocator_A3CoJWzService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\ProductController:new' => ['privates', '.service_locator.Hjz3HR0', 'get_ServiceLocator_Hjz3HR0Service', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.5OibA2.', 'get_ServiceLocator_5OibA2_Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.lwhU4dN', 'get_ServiceLocator_LwhU4dNService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\CartController::add' => '?',
            'App\\Controller\\CartController::delete' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\CartController::remove' => '?',
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\CommandController::add' => '?',
            'App\\Controller\\CommandController::index' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::new' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CartController:add' => '?',
            'App\\Controller\\CartController:delete' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\CartController:remove' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\CommandController:add' => '?',
            'App\\Controller\\CommandController:index' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:new' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
